version: '3.0'
services:
  api:
    image: richer1018/api:7.2.5
    ports:
      - 8888:8888
    hostname: "api"
    restart: always
    # swarm 設定
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.api == true ]
    environment:
      - TZ=Asia/Taipei
    networks:
      - my_network

networks:
  my_network:
    # 加入已經存在的網路
    external: true
