name: Run unit tests on Opened PR
on:
  pull_request:
    types: [ labeled ]

jobs:
  build-docker-image:
    if: ${{ github.event.label.name == 'test release' }}
    permissions:
      contents: read

    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."


