name: Run unit tests on Opened PR
on:
  pull_request:
    types: [ labeled ]

jobs:
  build-docker-image:
    if: ${{ github.event.label.name == 'test release' }}
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Retrieve the secret and decode it to a file
        env:
          LOCAL_CONFIG: ${{ secrets.LOCAL_CONFIG }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo $LOCAL_CONFIG | base64 --decode > local.ini
      - name: Build docker image
        run: |
          docker build -f Dockerfile -t richer1018/crawler:9.0.0 .
          docker login "richer1018" -p ${ DOCKER_HUB_TOKEN }
          docker push richer1018/crawler:9.0.0
          
      


